#pragma once

#include "Config.h"

extern Config *g_config;
#define CFG_CONFIG_NAME        "config.cfg"

#define CFG_STYLESHEET         "stylesheet"
#define CFG_CONNECTION         "connection"
#define CFG_STEPS_PER_MM       "stepsPermm"
#define CFG_MAX_VELOCITY       "maxVelocity"
#define CFG_MAX_ACCELERATION   "maxAcceleration"
#define CFG_USED_COORDS        "usedCoords"
#define CFG_SLAVE              "slave"
#define CFG_AXE_MAP            "axeMap"
#define CFG_INVERTED_AXES      "invertedAxes"
#define CFG_SWITCH_MIN         "switchMin"
#define CFG_SWITCH_MAX         "switchMax"
#define CFG_SWITCH_HOME        "switchHome"
#define CFG_SWITCH_POLARITY    "switchPolarity"
#define CFG_BACK_HOME          "backHome"
#define CFG_COORD_HOME         "coordHome"
#define CFG_HOMING             "homing"
#define CFG_FRACT_VALUE        "fractValue"
#define CFG_SLOW_PWM_FREQ      "slowPWMFreq"
#define CFG_PWM_FREQ           "PWMFreq"
#define CFG_G81_INCREMENTAL    "g81Incremental"
#define CFG_DEFAULT_ADC_USE    "defaultADCUse"
#define CFG_SPINDLE_MARKS      "spindleMarks"
#define CFG_SPINDLE_MARKS_PIN  "spindleMarksPin"
#define CFG_SPINDLE_MARKS_FREQ "spindleMarksFrequency"
#define CFG_SPINDLE_FILTER_SIZE "spindleFilterSize"
